include:
  - board: xiao_ble
#    shield: Pyuron_R rgbled_adapter
    shield: Pyuron_R
#    snippet: studio-rpc-usb-uart
  - board: xiao_ble
#    shield: Pyuron_L rgbled_adapter
    shield: Pyuron_L
  - board: xiao_ble
    shield: settings_reset
 
